services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: shop
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo
    restart: unless-stopped

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
      - mail-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shop
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_HOST: mail-dev
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: dolien
      SPRING_MAIL_PASSWORD: dolien
    restart: unless-stopped

  angular-app:
    build: ./shop-ui
    container_name: angular-app
    ports:
      - 80:80
    networks:
      - spring-demo
    depends_on:
      - spring-boot-app
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local