spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: dolien
    password: dolien
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000
  data:
    rest:
      detection-strategy: ANNOTATED

stripe:
  key:
    secret: sk_test_51PNFwp04tQ4vR1MnM2EzAroZuWFhVcwEBaRTxe1tOaKDZA8AMKwm7jO6ZucPPhrrn6FUh0ZZykqUksSQ57LMiacC001UXM20Du

application:
  security:
    jwt:
      secret-key: x9LQfzC9GIlFW8Hb2C6nA9wmnPLgGOUvLfMy7XOxUlbkFCAgsU
      expiration: 8640000
  mailing:
    frontend:
      activation-url: https://localhost:4200/activate-account
server:
  address: 0.0.0.0
  port: 8088
  ssl:
    enabled: true
    key-alias: dolien
    key-store: classpath:dolien-keystore.p12
    key-store-password: jXRaQtvd1n1KNN3N
    key-store-type: PKCS12